### ISSUE TITLE
SDSCOM XML examples

### ISSUE THREAD

**Issue by licausijf** [esdscom/sdscom-xml#81]
Dear,

Would it be possible to provide some real life examples of SDSCOM XML?
I have some difficulties to understand the use of some tag attributes and I do believe I could figure it out with some examples.

Thank you in advance for your feedback.

Regards,

@licausijf

**Comment by Suter-IK** [comment]
This could help you: [de_Isocyanate MDI 100.pdf](https://github.com/esdscom/sdscom-xml/files/227734/de_Isocyanate.MDI.100.pdf)
Btw, which company are you from?

**Comment by licausijf** [comment]
Thank you for your quick feedback. 
Would it be possible to also have the corresponding SDSCOM XML file? I think you only provided the SDS. Do you also have an English version of this SDS/SDSCOM XML?

I am working for LISAM Systems (http://www.lisam.com/).

**Comment by Suter-IK** [comment]
The document is PDF-A/3 and has the XML attached. Has anyone else here an English SDS?

**Comment by licausijf** [comment]
Thank you very much.

**Comment by pejas** [comment]
Thank you for this example. 
Are there any examples of LTS and version 5 that you could share?

**Comment by dirk-qualisys** [comment]
Not yet, unfortunately. All resources bound in reshaping web site and project - see esdscom.eu in a few days...

**Comment by Henrich-BGRCI** [comment]
We just published our GisChem data sheets of hazardous substances with an embedded SDScom in version 4.4.0.2. These data sheets are no real safety data sheets. Nevertheless, maybe it helps you as an example. Please, let me know, If you have any comments it.
For example, https://www.gischem.de/suche/dokument.htm?client_session_Dokument=2302 and https://www.gischem.de/download/01_0-000050-00-0-000000_1_1_3.PDF

**Comment by pejas-sustragil** [comment]
@Henrich-BGRCI thank you it is helpful.
I was looking (among other things) on MergePhrase usage (and I found it), still not sure how to embed multiple phrases with one place holder `...`. MergePhraseNo looks like a way to communicate ordinal of place holder. I believe it's not possible.

`Causes damage to ... if ....`

for 1st placeholder I have a list of `organs` and for 2nd single `route of exposure`. 
In this case MergePhraseNo would be "1" for organs and "2" for route.
I will have to do cartesian product on this node with organs so I will end up with as many H370 as I have organs.

Please do correct me if I am wrong or should create other issue in relation to this problem.

Anyway examples are very helpful at least for me. Thanks again.

**Comment by dirk-qualisys** [comment]
@pejas-sustragil : You can have more than one parameter in a phrase, but the number of merge phrases (bad wording - really a merge text!) must match the number of "..." inserts and the <MergePhrase>s are applied in order or appearance. There is no way to use a phrase, list of phrases or list of texts as one merge phrase, so you would need to connect the required content to a text covering the complete list "organ1, organ2, organ3 and organ4" first, and then insert this as a <MergePhrase>.

This was a heavy discussion a couple of years ago, because the <MergePhrase> is not translatable and thus pretty useless for text inserts IMHO, but it covers the case of numeric data like temperatures. This agreement was taken in the hope that more IT systems with lower phrase flexibility would adopt this format. Especially SAP can't digest phrase parameters in arbitrary places, instead it is limited to zero or none parameters at the end of a phrase. 

If you take a closer look at translations into languages with deviating grammar systems, it is an advantage to not use MergePhrase for complex issues like lists, but create a specific (non-standard / user) phrase without a parameter.

**Comment by Henrich-BGRCI** [comment]
Here is an example for using two MergePhrase in one sentense within section HazardLabelling: https://www.gischem.de/download/01_0-068479-98-1-000000_1_1_1132.PDF

**Comment by dirk-qualisys** [comment]
The above PDF is an A/3 file with included XML, containing (among others) these examples for a MergePhrase:

```
<ClpHazardStatement PhraseId="570">
            <PhraseCode>373</PhraseCode>
            <FullText>Kann ... ... schädigen bei längerer oder wiederholter Exposition.</FullText>
            <MergePhrase PhraseId="98" MergePhraseNo="1">
              <MergeText> bei Verschlucken</MergeText>
              <Delimiter>...</Delimiter>
            </MergePhrase>
            <MergePhrase PhraseId="" MergePhraseNo="2">
              <MergeText>die Organe</MergeText>
              <Delimiter>...</Delimiter>
            </MergePhrase>
          </ClpHazardStatement>
          <ClpPrecautionaryStatement PhraseId="25">
            <PhraseCode>260</PhraseCode>
            <FullText>... nicht einatmen.</FullText>
            <MergePhrase PhraseId="170" MergePhraseNo="1">
              <MergeText>Dampf/Aerosol/Nebel</MergeText>
              <Delimiter>...</Delimiter>
            </MergePhrase>
          </ClpPrecautionaryStatement>
```

Thank you for providing this, Mr. Henrich!
